### ISSUE TITLE
Implement a REST API endpoint for getting the questions of a quiz (exercise 12)

### ISSUE THREAD

**Issue by helikulomaa** [Team-417-Expectation-Failed/QuizzerApp#86]

**Comment by Jukalekvi** [comment]
Created the folder for api and dto files (Controllers etc)
Created QuizApiController.java
Created QuestionTDO.java

Updated Springboot from 3.3.5 to 3.4.0
Udated all tests to Mock instead of MockBean (new Springboot version doesn't support old version)

Updated QuestionRepository.java to retrieve all questions from a Quizz by the quizzes Id
Updated QuestionService.java methods and added comments to the methods to tell what they do ***
Updated AnswerOptionController.java
Updated QuizzerRestController.java

Added comments to AnswerOption.java
Added comments to AnswerOptionService.java

Fixed addQuizCategory.html template to allow adding a new category
